export const environment = {
  production: false,
  dbUsername: "daicatam001",
  dbPassword: "%40Bcdmon1",
  dbCluster: "cluster0.n5ikb",
  dbName: "authenticated",
  secretToken: "secret-token",
  jwtTokenExpire: 60,
  refreshTokenExpire: 86400,
  resetPasswordTokenExpire: 300,
  mailUsername: "phamthanhtam02095@gmail.com",
  mailPassword: "@bcdgma1",
  mailHost: "smtp.gmail.com",
  mailPort: 587,
};
